---
title: "Anna's code"
output: html_document
date: "2024-05-07"
---
Library
```{r}
options(scipen = 99)
library(Rcpp)
library(RcppArmadillo)
library(ggplot2)
library(readr)
library(tidyverse)
library(gridExtra)
#Rcpp::sourceCpp("logic/cpp/RungaKutta/RK4Markov.cpp")
```

Indlæs datasæt
```{r}
probabilities <- read_csv("probabilities.csv")
probabilities$månedsalder<-c(1:600)
View(probabilities)
```

Plots. Diskritiser til månedsniveau
Indvalide
```{r}

p_00<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_00))+
  geom_line()

p_01<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_01))+
  geom_line()

p_02<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_02))+
  geom_line()

p_10<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_10))+
  geom_line()

p_11<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_11))+
  geom_line()

p_12<-ggplot(data=probabilities,mapping=aes(x=månedsalder,y=p_12))+
  geom_line()

grid.arrange(p_00,p_01,p_02,p_10,p_11,p_12,nrow=2)
```

