```{r}
options(scipen = 99)
library(Rcpp)
library(RcppArmadillo)
library(ggplot2)
library(readr)
library(tidyverse)
library(gridExtra)
```

Data
```{r}
claims <- read_csv("claims.csv")
claims<-claims[,c(1,2)]
colnames(claims)<-c("claim_size","deductible")
claims<-mutate(claims,claim_size=claim_size/1000,deductible=deductible/1000)
freq <- read_csv("frequency.csv")
freq=freq%>%mutate(Age=log(Age+2),Brt=log(Brt),Dwt=log(Dwt),Value=log(Value),HP=log(HP))
View(claims)
view(freq)
claims$claim_adjusted<-claims$claim_size - claims$deductible
```

We have to change the data a little such that it our data will have an intercept and and hence we will expand the matrix such that each new column is a category for the categorial variable.
```{r}
freq=cbind(intercept=rep(1,nrow(freq)),freq)
```
```{r}
summary(freq)
#peter hvis du siger noget om min smukke kode så bliver jeg sur >:(
freq%>%mutate(
              Code2=if_else(Code1==2,1,0),
              Code3=if_else(Code1==3,1,0),
              Code9=if_else(Code1==4,1,0),
              Code5=if_else(Code1==5,1,0),
              Code6=if_else(Code1==6,1,0),
              Code7=if_else(Code1==7,1,0),
              Code8=if_else(Code1==8,1,0),
              Code3=if_else(Code1==9,1,0),
              Code1=if_else(Code1==1,1,0),
              Stroke0=if_else(Stroke==0,1,0),
              Stroke1=if_else(Stroke==1,1,0)
              )%>%select(!c(Stroke,Dedr,Time))

```


we use what is written on page 336 at the buttom since we have deductiable

```{r}
logLikeWDeductable<-function(beta,phi,data){
  nrow(data)*log(1+phi)
  sum=0
  for(i in 1:nrow(data)){
    
  }
  
  
}
```

