---
title: "Anna's code"
output: html_document
date: "2024-05-07"
---
Library
```{r}
options(scipen = 99)
library(Rcpp)
library(RcppArmadillo)
library(ggplot2)
library(readr)
library(tidyverse)
library(gridExtra)
```

Data
```{r}
claims <- read_csv("claims.csv")
claims<-claims[,c(1,2)]
colnames(claims)<-c("claim_size","deductible")
claims<-mutate(claims,claim_size=claim_size/1000,deductible=deductible/1000)
View(claims)

claims$claim_adjusted<-claims$claim_size - claims$deductible
```

Fit
```{r}
library(fitdistrplus)
#Lognormal
fit_lognormal <- fitdist(claims$claim_size-claims$deductible, "lnorm")
summary(fit_lognormal)

#Weibull
fit_weibull <- fitdist(claims$claim_size-claims$deductible, "weibull")
summary(fit_weibull)

#Pareto
fit_pareto <- fitdist(claims$claim_size-claims$deductible, "pareto")
summary(fit_pareto)

```

```{r}
E_X_star_minus_d <- function(d, fit, distribution) {
  if (distribution == "lnorm") {
    meanlog <- fit$estimate[1]
    sdlog <- fit$estimate[2]
    return(plnorm(d, meanlog, sdlog, lower.tail = FALSE) * 
             (exp(meanlog + 0.5 * sdlog^2) * (1 - pnorm((log(d) - meanlog - sdlog^2) / sdlog))))
  } else if (distribution == "weibull") {
    shape <- fit$estimate[1]
    scale <- fit$estimate[2]
    return(pweibull(d, shape, scale, lower.tail = FALSE) * 
             (scale * gamma(1 + 1/shape) * (1 - pweibull(d, shape + 1, scale))))
  } else if (distribution == "pareto") {
    shape <- fit$estimate[1]
    scale <- fit$estimate[2]
    if (d < scale) return(Inf)  # For Pareto, E[(X* - d)_+] is undefined for d < scale
    return((shape * scale^shape) / ((shape - 1) * d^(shape - 1)))
  }
}

d_values <- seq(0, 10000, by = 1)
lognormal_values <- sapply(d_values, E_X_star_minus_d, fit = fit_lognormal, distribution = "lnorm")
weibull_values <- sapply(d_values, E_X_star_minus_d, fit = fit_weibull, distribution = "weibull")
```

Plot
```{r}
plot(d_values, lognormal_values, type = "l", col = "blue", ylim = c(0, max(lognormal_values, weibull_values, na.rm = TRUE)), 
     ylab = "E[(X* - d)_+]", xlab = "d", main = "Expected value of (X* - d)_+ for different distributions")
lines(d_values, weibull_values, col = "red")

legend("topright", legend = c("Lognormal", "Weibull"), col = c("blue", "red"), lty = 1)
```

